### ISSUE TITLE
Btcpay incorrectly redirects noscript invoice

### ISSUE THREAD

**Issue by taxmeifyoucan** [Kixunil/cryptoanarchy-deb-repo-builder#101] opened 2020-10-31 00:58 UTC
Running `btcpayserver-system-mainnet` on `selfhost-onion`, it is by default on `http://....onion/btcpay`. If user has disabled javascript in his browser, Btcpay suggest redirect to  `javascript-disabled invoice`. This redirect link sends user to wrong address - `http://....onion/invoice-noscript?id=` which should be `http://....onion/btcpay/invoice-noscript?id=`. 

After inserting `btcpay/` manually, noscript invoice is there. However, button `Go back to Javascript enabled invoice` also provides incorrect address of standard invoice.

**Comment by Kixunil** [comment] 2020-11-02 09:13
This looks like a problem with BTCPayServer itself (root path ignored) but I didn't look into it deeply.
This project is not intended to be used with JS disabled anyway but may be useful for payers.

**Comment by taxmeifyoucan** [comment] 2020-11-02 10:51
I assumed that problem relates to repo since it works properly on normal Btcpay instances and it is caused by path created by default here. 
I believe it should be working, Btcpay supports it and users might prefer turn off javascript - only negative is loss of nice UX. 
Btcpay [redirects](https://github.com/btcpayserver/btcpayserver/blob/793b1b56d9b1a175111e6cc4027f8b2bc4bba4d0/BTCPayServer/Views/Invoice/Checkout.cshtml#L52) to `/invoice-noscript?id=`, is there a way of sending root path to `/btcpay` in this cases? Similar issue is when you want to use local resources like css or images, link is incorrect.

**Comment by Kixunil** [comment] 2020-11-02 16:43
Are you absolutely sure that in those docker deployments a root path different from `/` (e.g. `/btcpay`) is *also* used?

**Comment by taxmeifyoucan** [comment] 2020-11-07 18:22
I am not sure, I only worked with Btcpay on subdomain which uses `/` root path. However, since deb repo package by default uses `/btcpay`, features with redirects don't work, therefore I suggested it should be fixed on this side.

**Comment by Kixunil** [comment] 2020-11-07 22:04
Bug confirmed in the newest version of BTCPay.
BTW, there's another one: without JS crowdfunding appears inactive.

**Comment by Kixunil** [comment] 2020-11-07 22:28
Opened https://github.com/btcpayserver/btcpayserver/issues/2057

**Comment by Kixunil** [comment] 2020-11-28 21:16
This was fixed by BTCPayServer team and the fix is already packaged in beta. Closing as fixed.

**Closed by Kixunil** 2020-11-28 21:16 UTC
